# Generated by Django 5.0.1 on 2024-02-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_choice',
            field=models.CharField(choices=[('article', 'Статья'), ('news', 'Новость')], max_length=10),
        ),
    ]
