# Generated by Django 5.0.1 on 2024-02-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_post_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_choice',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], default='NE', max_length=2),
        ),
    ]
