# Generated by Django 5.0.1 on 2024-04-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_post_post_author_en_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title_en_us',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_ru',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
