# Generated by Django 5.0.1 on 2024-04-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_post_post_title_en_us_post_post_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text_ru',
            field=models.TextField(null=True),
        ),
    ]
