# Generated by Django 5.0.1 on 2024-04-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_category_thematic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thematic',
            field=models.CharField(choices=[('GS', 'Gossip'), ('PO', 'Politics'), ('TH', 'Technology'), ('BL', 'Breaking')], help_text='category name', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='thematic_en_us',
            field=models.CharField(choices=[('GS', 'Gossip'), ('PO', 'Politics'), ('TH', 'Technology'), ('BL', 'Breaking')], help_text='category name', max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='thematic_ru',
            field=models.CharField(choices=[('GS', 'Gossip'), ('PO', 'Politics'), ('TH', 'Technology'), ('BL', 'Breaking')], help_text='category name', max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_choice',
            field=models.CharField(choices=[('AR', 'Arcticle'), ('NW', 'News')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_choice_en_us',
            field=models.CharField(choices=[('AR', 'Arcticle'), ('NW', 'News')], default='NW', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_choice_ru',
            field=models.CharField(choices=[('AR', 'Arcticle'), ('NW', 'News')], default='NW', max_length=2, null=True),
        ),
    ]
