# Generated by Django 5.0.1 on 2024-04-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_category_thematic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_category_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_category_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_choice_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_choice_ru',
        ),
        migrations.DeleteModel(
            name='PostCategory_en_us',
        ),
        migrations.DeleteModel(
            name='PostCategory_ru',
        ),
    ]
